CC = 			gcc
CFLAGS = 		-Wall -Wextra -Werror
RM = 			rm -f

NAME = libft.a

SRCS = 			ft_isalpha.c ft_isdigit.c ft_isalnum.c ft_isascii.c \
				ft_isprint.c ft_strlen.c ft_memset.c ft_bzero.c ft_memcpy.c \
				ft_memmove.c ft_strlcpy.c ft_strlcat.c ft_toupper.c ft_tolower.c\
				ft_strchr.c ft_strrchr.c ft_strncmp.c ft_memchr.c ft_memcmp.c\
				ft_strnstr.c ft_atoi.c ft_calloc.c ft_strdup.c ft_substr.c\
				ft_strjoin.c ft_strtrim.c ft_split.c ft_itoa.c ft_strmapi.c \
				ft_striteri.c ft_putchar_fd.c ft_putstr_fd.c ft_putendl_fd.c ft_putnbr_fd.c\
				ft_lstnew.c \
				ft_lstadd_front.c \
				ft_lstsize.c \
				ft_lstlast.c \
				ft_lstadd_back.c \
				ft_lstdelone.c

OBJS = 		$(SRCS:.c=.o)

BONUS = 		ft_lstnew.c \
				ft_lstadd_front.c \
				ft_lstsize.c \
				ft_lstlast.c \
				ft_lstadd_back.c \
				ft_lstdelone.c

BOBJS = 	$(BONUS:.c=.o)

$(NAME) :	$(OBJS)
				ar -rc $(NAME) $(OBJS)

all : 		$(NAME)

so:
				$(CC) -nostartfiles -fPIC $(CFLAGS) $(SRCS)
				gcc -nostartfiles -shared -o libft.so $(OBJS) $(BOBJS)

.c.o:
				${CC} ${CFLAGS} -c $< -o ${<:.c=.o}


$(MSOURCES) :
				$(CC) $(CFLAGS) $(SRCS) -c
				ar -rc $(NAME) $(OBJS)

$(BSOURCES) :
				$(CC) $(CFLAGS) $(SRCS) -c
				ar -rc $(NAME) $(OBJS)

re : 		fclean all

bonus: 		$(BOBJS)
				ar -rc $(NAME) $(BOBJS)

clean:
				$(RM) $(OBJS) $(BOBJS)

fclean: 	clean
				$(RM) $(NAME)
				$(RM) libft.so

.PHONY: 	fclean clean re all bonus